import { createElement } from 'react'

export const BarChart = ({ children, ...props }) => createElement('div', { 'data-testid': 'bar-chart', ...props }, children)
export const Bar = (props) => createElement('div', { 'data-testid': 'bar', ...props })
export const LineChart = ({ children, ...props }) => createElement('div', { 'data-testid': 'line-chart', ...props }, children)
export const Line = (props) => createElement('div', { 'data-testid': 'line', ...props })
export const PieChart = ({ children, ...props }) => createElement('div', { 'data-testid': 'pie-chart', ...props }, children)
export const Pie = (props) => createElement('div', { 'data-testid': 'pie', ...props })
export const AreaChart = ({ children, ...props }) => createElement('div', { 'data-testid': 'area-chart', ...props }, children)
export const Area = (props) => createElement('div', { 'data-testid': 'area', ...props })
export const ScatterChart = ({ children, ...props }) => createElement('div', { 'data-testid': 'scatter-chart', ...props }, children)
export const Scatter = (props) => createElement('div', { 'data-testid': 'scatter', ...props })
export const RadarChart = ({ children, ...props }) => createElement('div', { 'data-testid': 'radar-chart', ...props }, children)
export const Radar = (props) => createElement('div', { 'data-testid': 'radar', ...props })
export const ComposedChart = ({ children, ...props }) => createElement('div', { 'data-testid': 'composed-chart', ...props }, children)
export const XAxis = (props) => createElement('div', { 'data-testid': 'x-axis', ...props })
export const YAxis = (props) => createElement('div', { 'data-testid': 'y-axis', ...props })
export const CartesianGrid = (props) => createElement('div', { 'data-testid': 'cartesian-grid', ...props })
export const Tooltip = (props) => createElement('div', { 'data-testid': 'tooltip', ...props })
export const Legend = (props) => createElement('div', { 'data-testid': 'legend', ...props })
export const ResponsiveContainer = ({ children, ...props }) => createElement('div', { 'data-testid': 'responsive-container', ...props }, children)
export const Cell = (props) => createElement('div', { 'data-testid': 'cell', ...props })
export const PolarGrid = (props) => createElement('div', { 'data-testid': 'polar-grid', ...props })
export const PolarAngleAxis = (props) => createElement('div', { 'data-testid': 'polar-angle-axis', ...props })
export const PolarRadiusAxis = (props) => createElement('div', { 'data-testid': 'polar-radius-axis', ...props })
